package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ByteArray generated by hbm2java
 */
@Entity
@Table(name = "act_ge_bytearray")
public class ByteArray {

    public ByteArray() {
    }

    public ByteArray(String id) {
        this.id = id;
    }

    public ByteArray(String id, Deployment deployment, Integer rev, String name, byte[] bytes, Boolean generated, Set<Model> modelsForEditorSourceValueId, Set<Job> jobs, Set<ProcessDefinitionInfo> processDefinitionInfos, Set<Model> modelsForEditorSourceExtraValueId, Set<VariableInstance> variableInstances) {
        this.id = id;
        this.deployment = deployment;
        this.rev = rev;
        this.name = name;
        this.bytes = bytes;
        this.generated = generated;
        this.modelsForEditorSourceValueId = modelsForEditorSourceValueId;
        this.jobs = jobs;
        this.processDefinitionInfos = processDefinitionInfos;
        this.modelsForEditorSourceExtraValueId = modelsForEditorSourceExtraValueId;
        this.variableInstances = variableInstances;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deployment_id_")
    Deployment deployment

    @Column(name = "rev_")
    Integer rev

    @Column(name = "name_")
    String name

    @Column(name = "bytes_")
    public byte[] getBytes() {
        return this.bytes;
    }

    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }

    @Column(name = "generated_")
    Boolean generated

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "byteArrayByEditorSourceValueId")
    Set<Model> modelsForEditorSourceValueId

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "byteArray")
    Set<Job> jobs

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "byteArray")
    Set<ProcessDefinitionInfo> processDefinitionInfos

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "byteArrayByEditorSourceExtraValueId")
    Set<Model> modelsForEditorSourceExtraValueId

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "byteArray")
    Set<VariableInstance> variableInstances
}


