package org.activiti.springdatajpa.models

import com.fasterxml.jackson.annotation.JsonIdentityInfo
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * EventLogEntry generated by hbm2java
 */
@Entity
@Table(name = "act_evt_log")
@JsonIdentityInfo(generator = ObjectIdGenerators.UUIDGenerator)
public class EventLogEntry {

    public EventLogEntry() {
    }

    public EventLogEntry(int logNr, Date timeStamp) {
        this.logNr = logNr;
        this.timeStamp = timeStamp;
    }

    public EventLogEntry(int logNr, String type, String procDefId, String procInstId, String executionId, String taskId, Date timeStamp, String userId, byte[] data, String lockOwner, Date lockTime, Short isProcessed) {
        this.logNr = logNr;
        this.type = type;
        this.procDefId = procDefId;
        this.procInstId = procInstId;
        this.executionId = executionId;
        this.taskId = taskId;
        this.timeStamp = timeStamp;
        this.userId = userId;
        this.data = data;
        this.lockOwner = lockOwner;
        this.lockTime = lockTime;
        this.isProcessed = isProcessed;
    }

    @Id
    @Column(name = "log_nr_", unique = true, nullable = false)
    int logNr

    @Column(name = "type_", length = 64)
    String type

    @Column(name = "proc_def_id_", length = 64)
    String procDefId

    @Column(name = "proc_inst_id_", length = 64)
    String procInstId

    @Column(name = "execution_id_", length = 64)
    String executionId

    @Column(name = "task_id_", length = 64)
    String taskId

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "time_stamp_", nullable = false, length = 29)
    Date timeStamp

    @Column(name = "user_id_")
    String userId

    @Column(name = "data_")
    public byte[] getData() {
        return this.data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    @Column(name = "lock_owner_")
    String lockOwner

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lock_time_", length = 29)
    Date lockTime

    @Column(name = "is_processed_")
    Short isProcessed
}


