package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * HistoricDetail generated by hbm2java
 */
@Entity
@Table(name = "act_hi_detail")
public class HistoricDetail {

    public HistoricDetail() {
    }

    public HistoricDetail(String id, String type, String name, Date time) {
        this.id = id;
        this.type = type;
        this.name = name;
        this.time = time;
    }

    public HistoricDetail(String id, String type, String procInstId, String executionId, String taskId, String actInstId, String name, String varType, Integer rev, Date time, String bytearrayId, Double double_, Long long_, String text, String text2) {
        this.id = id;
        this.type = type;
        this.procInstId = procInstId;
        this.executionId = executionId;
        this.taskId = taskId;
        this.actInstId = actInstId;
        this.name = name;
        this.varType = varType;
        this.rev = rev;
        this.time = time;
        this.bytearrayId = bytearrayId;
        this.double_ = double_;
        this.long_ = long_;
        this.text = text;
        this.text2 = text2;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @Column(name = "type_", nullable = false)
    String type

    @Column(name = "proc_inst_id_", length = 64)
    String procInstId

    @Column(name = "execution_id_", length = 64)
    String executionId

    @Column(name = "task_id_", length = 64)
    String taskId

    @Column(name = "act_inst_id_", length = 64)
    String actInstId

    @Column(name = "name_", nullable = false)
    String name

    @Column(name = "var_type_", length = 64)
    String varType

    @Column(name = "rev_")
    Integer rev

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "time_", nullable = false, length = 29)
    Date time

    @Column(name = "bytearray_id_", length = 64)
    String bytearrayId

    @Column(name = "double_", precision = 17, scale = 17)
    Double double_

    @Column(name = "long_")
    Long long_

    @Column(name = "text_", length = 4000)
    String text

    @Column(name = "text2_", length = 4000)
    String text2
}


