package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HistoricIdentityLink generated by hbm2java
 */
@Entity
@Table(name = "act_hi_identitylink")
public class HistoricIdentityLink {








    public HistoricIdentityLink() {
    }

    public HistoricIdentityLink(String id) {
        this.id = id;
    }

    public HistoricIdentityLink(String id, String groupId, String type, String userId, String taskId, String proccessInstanceId) {
        this.id = id;
        this.groupId = groupId;
        this.type = type;
        this.userId = userId;
        this.taskId = taskId;
        this.proccessInstanceId = proccessInstanceId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @Column(name = "group_id_")
    String groupId

    @Column(name = "type_")
    String type

    @Column(name = "user_id_")
    String userId

    @Column(name = "task_id_", length = 64)
    String taskId

    @Column(name = "proc_inst_id_", length = 64)
    String proccessInstanceId
}


