package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * HistoricVariableInstance generated by hbm2java
 */
@Entity
@Table(name = "act_hi_varinst")
public class HistoricVariableInstance {
















    public HistoricVariableInstance() {
    }

    public HistoricVariableInstance(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public HistoricVariableInstance(String id, String processInstanceId, String executionId, String taskId, String name, String varType, Integer rev, String bytearrayId, Double double_, Long long_, String text, String text2, Date createTime, Date lastUpdatedTime) {
        this.id = id;
        this.processInstanceId = processInstanceId;
        this.executionId = executionId;
        this.taskId = taskId;
        this.name = name;
        this.varType = varType;
        this.rev = rev;
        this.bytearrayId = bytearrayId;
        this.double_ = double_;
        this.long_ = long_;
        this.text = text;
        this.text2 = text2;
        this.createTime = createTime;
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @Column(name = "proc_inst_id_", length = 64)
    String processInstanceId

    @Column(name = "execution_id_", length = 64)
    String executionId

    @Column(name = "task_id_", length = 64)
    String taskId

    @Column(name = "name_", nullable = false)
    String name

    @Column(name = "var_type_", length = 100)
    String varType

    @Column(name = "rev_")
    Integer rev

    @Column(name = "bytearray_id_", length = 64)
    String bytearrayId

    @Column(name = "double_", precision = 17, scale = 17)
    Double double_

    @Column(name = "long_")
    Long long_

    @Column(name = "text_", length = 4000)
    String text

    @Column(name = "text2_", length = 4000)
    String text2

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time_", length = 29)
    Date createTime

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_updated_time_", length = 29)
    Date lastUpdatedTime
}


