package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * HistoricActivityInstance generated by hbm2java
 */
@Entity
@Table(name = "act_hi_actinst")
public class HistoricActivityInstance {

    public HistoricActivityInstance() {
    }

    public HistoricActivityInstance(String id, String procDefId, String procInstId, String executionId, String actId, String actType, Date startTime) {
        this.id = id;
        this.procDefId = procDefId;
        this.procInstId = procInstId;
        this.executionId = executionId;
        this.actId = actId;
        this.actType = actType;
        this.startTime = startTime;
    }

    public HistoricActivityInstance(String id, String procDefId, String procInstId, String executionId, String actId, String taskId, String callProcInstId, String actName, String actType, String assignee, Date startTime, Date endTime, Long duration, String tenantId) {
        this.id = id;
        this.procDefId = procDefId;
        this.procInstId = procInstId;
        this.executionId = executionId;
        this.actId = actId;
        this.taskId = taskId;
        this.callProcInstId = callProcInstId;
        this.actName = actName;
        this.actType = actType;
        this.assignee = assignee;
        this.startTime = startTime;
        this.endTime = endTime;
        this.duration = duration;
        this.tenantId = tenantId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @Column(name = "proc_def_id_", nullable = false, length = 64)
    String procDefId

    @Column(name = "proc_inst_id_", nullable = false, length = 64)
    String procInstId

    @Column(name = "execution_id_", nullable = false, length = 64)
    String executionId

    @Column(name = "act_id_", nullable = false)
    String actId

    @Column(name = "task_id_", length = 64)
    String taskId

    @Column(name = "call_proc_inst_id_", length = 64)
    String callProcInstId

    @Column(name = "act_name_")
    String actName

    @Column(name = "act_type_", nullable = false)
    String actType

    @Column(name = "assignee_")
    String assignee

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time_", nullable = false, length = 29)
    Date startTime

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time_", length = 29)
    Date endTime

    @Column(name = "duration_")
    Long duration

    @Column(name = "tenant_id_")
    String tenantId
}


