package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * HistoricTaskInstance generated by hbm2java
 */
@Entity
@Table(name = "act_hi_taskinst")
public class HistoricTaskInstance {

    public HistoricTaskInstance() {
    }

    public HistoricTaskInstance(String id, Date startTime) {
        this.id = id;
        this.startTime = startTime;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @Column(name = "proc_def_id_", length = 64)
    String processDefinitionId

    @Column(name = "task_def_key_")
    String taskDefinitionKey

    @Column(name = "proc_inst_id_", length = 64)
    String processInstanceId

    @Column(name = "execution_id_", length = 64)
    String executionId

    @Column(name = "name_")
    String name

    @Column(name = "parent_task_id_", length = 64)
    String parentTaskId

    @Column(name = "description_", length = 4000)
    String description

    @Column(name = "owner_")
    String owner

    @Column(name = "assignee_")
    String assignee

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time_", nullable = false, length = 29)
    Date startTime

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "claim_time_", length = 29)
    Date claimTime

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time_", length = 29)
    Date endTime

    @Column(name = "duration_")
    Long duration

    @Column(name = "delete_reason_", length = 4000)
    String deleteReason

    @Column(name = "priority_")
    Integer priority

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "due_date_", length = 29)
    Date dueDate

    @Column(name = "form_key_")
    String formKey

    @Column(name = "category_")
    String category

    @Column(name = "tenant_id_")
    String tenantId
}


