package org.activiti.springdatajpa.models

import com.fasterxml.jackson.annotation.JsonIdentityInfo
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA



import org.activiti.springdatajpa.models.enums.IdentityLinkType
import org.activiti.springdatajpa.repositories.IdentityInfoRepository;
import org.activiti.springdatajpa.repositories.IdentityLinkRepository;
import org.springframework.beans.factory.annotation.Autowired;

import javax.persistence.*;

import static javax.persistence.EnumType.STRING;

/**
 * IdentityLink generated by hbm2java
 */
@Entity
@Table(name = "act_ru_identitylink")
@JsonIdentityInfo(generator = ObjectIdGenerators.UUIDGenerator)
public class IdentityLink {

    public IdentityLink() {
    }

    public IdentityLink(String id) {
        this.id = id;
    }


    public IdentityLink(Execution processInstance, String groupId, IdentityLinkType type, String userId) {
        this.processInstance = processInstance;
        this.groupId = groupId;
        this.type = type;
        this.userId = userId;
    }

    public IdentityLink(String id, ProcessDefinition processDefinition, Task task, Execution processInstance, Integer rev, String groupId, IdentityLinkType type, String userId) {
        this.id = id;
        this.processDefinition = processDefinition;
        this.task = task;
        this.processInstance = processInstance;
        this.rev = rev;
        this.groupId = groupId;
        this.type = type;
        this.userId = userId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_def_id_")
    ProcessDefinition processDefinition

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id_")
    Task task

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_inst_id_")
    Execution processInstance

    @Column(name = "rev_")
    Integer rev

    @Column(name = "group_id_")
    String groupId

    @Column(name = "type_")
    @Enumerated(STRING)
    IdentityLinkType type

    @Column(name = "user_id_")
    String userId

    ///transients

    @Transient
    private IdentityLinkRepository identityLinkRepository

    @Autowired
    public void setIdentityRepository(IdentityLinkRepository _identityLinkRepository) {
        identityLinkRepository = _identityLinkRepository
    }

    @Transient
    Boolean isUser() {  userId != null }

    IdentityLink insert() {
        identityLinkRepository.save(this)
    }
}


