package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "act_ru_job")
public class Job {



















    public Job() {
    }

    public Job(String id, String type) {
        this.id = id;
        this.type = type;
    }

    public Job(String id, ByteArray byteArray, Integer rev, String type, Date lockExpTime, String lockOwner, Boolean exclusive, String executionId, String processInstanceId, String procDefId, Integer retries, String exceptionMsg, Date duedate, String repeat, String handlerType, String handlerCfg, String tenantId) {
        this.id = id;
        this.byteArray = byteArray;
        this.rev = rev;
        this.type = type;
        this.lockExpTime = lockExpTime;
        this.lockOwner = lockOwner;
        this.exclusive = exclusive;
        this.executionId = executionId;
        this.processInstanceId = processInstanceId;
        this.procDefId = procDefId;
        this.retries = retries;
        this.exceptionMsg = exceptionMsg;
        this.duedate = duedate;
        this.repeat = repeat;
        this.handlerType = handlerType;
        this.handlerCfg = handlerCfg;
        this.tenantId = tenantId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exception_stack_id_")
    ByteArray byteArray

    @Column(name = "rev_")
    Integer rev

    @Column(name = "type_", nullable = false)
    String type

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lock_exp_time_", length = 29)
    Date lockExpTime

    @Column(name = "lock_owner_")
    String lockOwner

    @Column(name = "exclusive_")
    Boolean exclusive

    @Column(name = "execution_id_", length = 64)
    String executionId

    @Column(name = "process_instance_id_", length = 64)
    String processInstanceId

    @Column(name = "proc_def_id_", length = 64)
    String procDefId

    @Column(name = "retries_")
    Integer retries

    @Column(name = "exception_msg_", length = 4000)
    String exceptionMsg

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "duedate_", length = 29)
    Date duedate

    @Column(name = "repeat_")
    String repeat

    @Column(name = "handler_type_")
    String handlerType

    @Column(name = "handler_cfg_", length = 4000)
    String handlerCfg

    @Column(name = "tenant_id_")
    String tenantId
}


