package org.activiti.springdatajpa.models

import com.fasterxml.jackson.annotation.JsonIdentityInfo
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name = "act_re_model")
@JsonIdentityInfo(generator = ObjectIdGenerators.UUIDGenerator)
public class Model {

    public Model() {
    }

    public Model(String id) {
        this.id = id;
    }

    public Model(String id, ByteArray byteArrayByEditorSourceValueId, Deployment deployment, ByteArray byteArrayByEditorSourceExtraValueId, Integer rev, String name, String key, String category, Date createTime, Date lastUpdateTime, Integer version, String metaInfo, String tenantId) {
        this.id = id;
        this.byteArrayByEditorSourceValueId = byteArrayByEditorSourceValueId;
        this.deployment = deployment;
        this.byteArrayByEditorSourceExtraValueId = byteArrayByEditorSourceExtraValueId;
        this.rev = rev;
        this.name = name;
        this.key = key;
        this.category = category;
        this.createTime = createTime;
        this.lastUpdateTime = lastUpdateTime;
        this.version = version;
        this.metaInfo = metaInfo;
        this.tenantId = tenantId;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "editor_source_value_id_")
    ByteArray byteArrayByEditorSourceValueId

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "deployment_id_")
    Deployment deployment

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "editor_source_extra_value_id_")
    ByteArray byteArrayByEditorSourceExtraValueId

    @Column(name = "rev_")
    Integer rev

    @Column(name = "name_")
    String name

    @Column(name = "key_")
    String key

    @Column(name = "category_")
    String category

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time_", length = 29)
    Date createTime

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_time_", length = 29)
    Date lastUpdateTime

    @Column(name = "version_")
    Integer version

    @Column(name = "meta_info_", length = 4000)
    String metaInfo

    @Column(name = "tenant_id_")
    String tenantId
}


