package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * ProcessDefinitionInfo generated by hbm2java
 */
@Entity
@Table(name = "act_procdef_info",
        uniqueConstraints = @UniqueConstraint(columnNames = "proc_def_id_")
)
public class ProcessDefinitionInfo {

    public ProcessDefinitionInfo() {
    }

    public ProcessDefinitionInfo(String id, ProcessDefinition processDefinition) {
        this.id = id;
        this.processDefinition = processDefinition;
    }

    public ProcessDefinitionInfo(String id, ProcessDefinition processDefinition, ByteArray byteArray, Integer rev) {
        this.id = id;
        this.processDefinition = processDefinition;
        this.byteArray = byteArray;
        this.rev = rev;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proc_def_id_", unique = true, nullable = false)
    ProcessDefinition processDefinition

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "info_json_id_")
    ByteArray byteArray

    @Column(name = "rev_")
    Integer rev
}


