package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessDefinition generated by hbm2java
 */
@Entity
@Table(name = "act_re_procdef"
        , uniqueConstraints = @UniqueConstraint(columnNames = ["key_", "version_", "tenant_id_"])
)
public class ProcessDefinition {

    public ProcessDefinition() {
    }

    public ProcessDefinition(String id, String key, int version) {
        this.id = id;
        this.key = key;
        this.version = version;
    }

    public ProcessDefinition(String id, Integer rev, String category, String name, String key, int version, String deploymentId, String resourceName, String dgrmResourceName, String description, Boolean hasStartFormKey, Boolean hasGraphicalNotation, Integer suspensionState, String tenantId, Set<Execution> executions, Set<ProcessDefinitionInfo> processDefinitionInfos, Set<Task> tasks, Set<IdentityLink> identityLinks) {
        this.id = id;
        this.rev = rev;
        this.category = category;
        this.name = name;
        this.key = key;
        this.version = version;
        this.deploymentId = deploymentId;
        this.resourceName = resourceName;
        this.dgrmResourceName = dgrmResourceName;
        this.description = description;
        this.hasStartFormKey = hasStartFormKey;
        this.hasGraphicalNotation = hasGraphicalNotation;
        this.suspensionState = suspensionState;
        this.tenantId = tenantId;
        this.executions = executions;
        this.processDefinitionInfos = processDefinitionInfos;
        this.tasks = tasks;
        this.identityLinks = identityLinks;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @Column(name = "rev_")
    Integer rev

    @Column(name = "category_")
    String category

    @Column(name = "name_")
    String name

    @Column(name = "key_", nullable = false)
    String key

    @Column(name = "version_", nullable = false)
    int version

    @Column(name = "deployment_id_", length = 64)
    String deploymentId

    @Column(name = "resource_name_", length = 4000)
    String resourceName

    @Column(name = "dgrm_resource_name_", length = 4000)
    String dgrmResourceName

    @Column(name = "description_", length = 4000)
    String description

    @Column(name = "has_start_form_key_")
    Boolean hasStartFormKey

    @Column(name = "has_graphical_notation_")
    Boolean hasGraphicalNotation

    @Column(name = "suspension_state_")
    Integer suspensionState

    @Column(name = "tenant_id_")
    String tenantId

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "processDefinition")
    Set<Execution> executions

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "processDefinition")
    Set<ProcessDefinitionInfo> processDefinitionInfos

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "processDefinition")
    Set<Task> tasks

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "processDefinition")
    Set<IdentityLink> identityLinks
}


