package org.activiti.springdatajpa.models;
// Generated Nov 21, 2015 11:41:58 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "act_id_user")
public class User {

    public User() {
    }

    public User(String id) {
        this.id = id;
    }

    public User(String id, Integer rev, String first, String last, String email, String pwd, String pictureId, Set<Group> groups) {
        this.id = id;
        this.rev = rev;
        this.first = first;
        this.last = last;
        this.email = email;
        this.pwd = pwd;
        this.pictureId = pictureId;
        this.groups = groups;
    }

    @Id
    @Column(name = "id_", unique = true, nullable = false, length = 64)
    String id

    @Column(name = "rev_")
    Integer rev

    @Column(name = "first_")
    String first

    @Column(name = "last_")
    String last

    @Column(name = "email_")
    String email

    @Column(name = "pwd_")
    String pwd

    @Column(name = "picture_id_", length = 64)
    String pictureId

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "act_id_membership", schema = "public",
            joinColumns = [@JoinColumn(name = "user_id_", nullable = false, updatable = false)],
            inverseJoinColumns = [@JoinColumn(name = "group_id_", nullable = false, updatable = false)])
    Set<Group> groups
}


